### ISSUE TITLE
Contouring Error and Lag Error Weights

### ISSUE THREAD

**Issue by PranjaLBiswas27** [alexliniger/MPCC#12]
Hi @alexliniger ,

I was trying to tune the weights of contouring error (qc) and lag error (ql). I understand that  lag error weight should be large to have accurate error approximation, but in what order of magnitude the weights should ideally be? Any good starting point for tuning?

Kind Reagrds
Pranjal Biswas

**Comment by alexliniger** [comment]
For the setup as it is I got good results for:
0 <= q_c <= 10, with no real change for values smaller than ~0.2, I never checked when increasing  q_c does not have an influence.
normally I used q_l = 500 or 1000 and did no tunning, however, this value also depends on the progress maximization.
Also really important is qVtheta, where I got good results for 0.015 <= qVtheta <= 0.025, however this changes when you change the sampling time, and I got good results for values roughly the sampling time.
