### ISSUE TITLE
Arc-length State Initialization

### ISSUE THREAD

**Issue by PranjaLBiswas27** [alexliniger/MPCC#14]
Hi @alexliniger ,

If I understand the paper referenced in this repository correctly, arc-length of the parameterized path acts as one of the states for MPCC. And at each time step all states need to be initialized using the actual current states of the vehicle to predict over the prediction horizon. What is the best way to initialize arc-length (theta)? Is it advisable to just take the previous time step predicted arc-length, or should one calculate the exact optimal arc-length by projecting the current vehicle position on to the parameterized reference path i.e. solve Eq. 8 at each MPCC time step just for initialization of one state? Please let me know.

Kind Regards

Pranjal Biswas

**Comment by alexliniger** [comment]
You can see in the code that I used the findTheta function to compute the arc length of the current position (theta_0), however, all the other thetas are taken from the previous solution (which is shifted in the function augState)
I hope this helps,
Alex
