### ISSUE TITLE
Track Constraints

### ISSUE THREAD

**Issue by PranjaLBiswas27** [alexliniger/MPCC#15]
Hi @alexliniger ,

In the paper you define tracks constraint using a pair of half-spaces over the prediction horizon. From what I understand these constraints will vary over the prediction horizon and are not really known beforehand.  I have few questions in relation to this:

1)  Just to confirm halfspaces represent linear equations of line, parametrized by state X and Y (position of the vehicle)?

2) How exactly can i formulate constraints which will vary over prediction horizon and are not known before hand, as it will depend on position of the vehicle at any given prediction step. I am only aware of defining constraints and then solving the optimization problem, any references?

3) The paper (Figure 4) says the green points on borders are projection of the center line points. How exactly is this projection evaluated, it is not very clear to me. 

Please let me know.

Kind Regards

Pranjal Biswas

**Comment by alexliniger** [comment]
Yes the constraints do vary over the horizon, there is even a figure in the paper illustrating this.
1. yes half spaces are just lines, **one** half space looks like this [a,b]*[X;Y] <= c, where a,b,c determine the half space. You can see in the code how a,b and c are computed.
2. For each time step in your prediction horizon you know approximately the theta value, by using the old solution and shifting it (this is the general idea of real time iterations, and basically the answer to all your question). This then allows you to query the center line and border splines and get the position of the borders as well as the derivatives, which again allows you to compute the half spaces.
3. In the MPCC, theta is an approximation of the projection, and I just use theta from the previous iterations as explained in the answer to 2. (in the hrhc the projection is performed using a function similar to the findTheta function)

Best, 
Alex
