### ISSUE TITLE
Discretization of the affine term of Linearized System

### ISSUE THREAD

**Issue by PranjaLBiswas27** [alexliniger/MPCC#17]
https://github.com/alexliniger/MPCC/blob/6a5529b8453432e62d9806e2fd5bc020cf872c8a/Matlab/DiscretizedLinearizedModel.m#L168

Hi @alexliniger 

In the above link you discretize the affine term (gc), but I do not understand how the math follows here. Do you have any reference for the same? 

Regards

Pranjal

**Comment by alexliniger** [comment]
This was already an issue, see the answer here:
https://github.com/alexliniger/MPCC/issues/9

**Comment by PranjaLBiswas27** [comment]
Ahh did not see that, thanks.
