### ISSUE TITLE
cmake version differences

### ISSUE THREAD

**Issue by chentairan** [alexliniger/MPCC#25]
Hi @alexliniger 

Thank you very much for providing the C ++ version, which will be of great help to my study and research.

One of the little things I want to ask you. When I build the C ++ version in Ubuntu 16.04 cmake 3.5.2 environment, it prompts me that the cmake version is too low. I tried to modify the minimum version limit of the CMakeLists.txt file, and the compilation was successful. 

So does different cmake versions affect the performance of the MPCC?

I wish you a Happy New Year 2020 !

Best,
Tairan Chen

**Comment by alexliniger** [comment]
I am not a cmake expert but I think the cmake version check is a safeguard against new features in cmake older versions do not support. 
But there is nothing fancy in the camke file and I think there should be no drawbacks.
Only the actual compiler you use gcc in your case should influence the performance, but again I assume this to be neglectable.
Best,
Alex
