### ISSUE TITLE
Model Predictive Reference Tracking Control vs Model Predictive Path Following Control

### ISSUE THREAD

**Issue by PranjaLBiswas27** [alexliniger/MPCC#3]
Hi @alexliniger ,

I don't know if its the right place for this query but am really curious about it, so I will put it here so that it might be useful for others as well.

I have been reading on Model Predictive Reference Tracking Control and Model Predictive Path Following Control (MPFC) both. While you have used MPFC in a MPCC framework in the paper here, you mention that only issue with MPCC arises in cases of significant model mismatch and no more limitations other than that have been highlighted in the paper if I am correct.  Since my understanding of MPFC is quite new, it is very fascinating to me in the sense that a optimized velocity profile can be evaluated using just a reference path parametrized by arc length. This makes me wonder than is at all required to generate reference trajectory profiles for applications related to autonomous driving which either requires time consuming non-linear optimization or are many times hand curated which is not optimal. Thus in that sense MPCC approach totally outweighs reference tracking approach. But since I believe in the philosophy of "No Free Lunch", I believe there might as well be a drawback to using an MPCC approach, although I am not able to get my head around that. So, my question here will be in your opinion can MPCC be sure shot solution to low level motion planning for applications of autonomous driving (urban and racing both), or there is still a drawback to it which will limit its usage?

Really looking forward to hear from you.

Kind Regards
Pranjal Biswas

**Comment by alexliniger** [comment]
There are always drawbacks. 
1. Before this MPCC approach can be used for autonomous driving you need to include suited comfort costs and constraints. 
2. MPC methods always go to the allowed "limits", which is not what you always want in autonomous driving. Thus, you need to add some measures, for example, I investigated stochastic MPC.
3. MPC methods are bad at binary decision making, in the racing example, this is highlighted by the decision on which side the car should avoid the obstacle. Thus, you need an upper level which does some smart planning.
4. You need to couple layers in your driving stack, such that the lower level can execute what the upper level intended.

Some general comments, this method is performing what a lot of people call time-consuming non-linear optimization, we just made a lot of progress in terms of solution methods for this problem class which allows to solve them in real time now. Generally, I prefer path following methods for their flexibility this is especially true in autonomous driving, also it is still possible to couple them do a reference if wanted. 

And now there is not THE method to use, there are even quite a lot of different path following methods all with there advantages and disadvantages.
