### ISSUE TITLE
Selection of reference path spacing

### ISSUE THREAD

**Issue by chentairan** [alexliniger/MPCC#51]
Hi @alexliniger 

I see that in the code, you approximate the arc length by the straight-line distance between two points.

![image](https://user-images.githubusercontent.com/24427334/92614309-7d818580-f2ee-11ea-8dc3-9077219de83c.png)

Thus, If I understand the code correctly, the arc length error will be larger when the distance between the two points is large. So I have one question:

1. Whether the distance between the input reference path points should be as small as possible.

Thanks
Tairan Chen

**Comment by alexliniger** [comment]
I tested this and it doesn't make a big difference, the quality of the curvature really depends on the reference path, something like the orca track which has not smooth derivatives does not work well. There are other splines that are better suited for the task of fitting a 2D curves.
