### ISSUE TITLE
Normalisation for QP

### ISSUE THREAD

**Issue by dwirya** [alexliniger/MPCC#52]
Hi Alex,

I'm currently new to optimisation theory and I don't quite follow why we need to normalise the QP problem as seen in your C++ code. Does this result in obtaining the solution faster ? Additionally, how did you get the normalisation parameters ? Thank you in advance.

Regards,
Dennis

**Comment by alexliniger** [comment]
Sometimes normalization can help, especially if some of the states and actions are in completely different ranges, but this is more related to numerical issues.
The normalization parameters are just chosen such that the states are in the +/- 1 range. But generally it is not really necessary, in the full size version it works good without normalization. The main branch does not work well for full sized cars.
Best,
Alex

**Comment by dwirya** [comment]
I see, thank you for the clarification!

Kind regards,
Dennis
