### ISSUE TITLE
About the State Parameters

### ISSUE THREAD

**Issue by naveenkumar4922** [alexliniger/MPCC#61]
Hello, i have one Doubt . In the Main file Your Representing states of X0 with 10 parameters, that was sending to the solver. i want to know that what are the parameters are to sending to solver and also X0.s also you are using i don't know what the use of it.

**Comment by alexliniger** [comment]
The state is x0 = [X, Y, phi, v_x, v_y, r, s, d, delta, v_s]
X-Y -> position
phi -> heading
v_x -> longitudinal velocity
v_y -> longitudinal velocity
r -> yaw rate
s -> arc length along the reference path (middle line)
d -> duty cycle
delta -> steering
v_s -> velocity along the reference path

if you take an X-Y point and project it on the reference path, the arc length of this point is 's'

I hope this helps,
Alex
