### ISSUE TITLE
C++ build error

### ISSUE THREAD

**Issue by Geonhee-LEE** [alexliniger/MPCC#72]
Hi, @alexliniger.
Thanks for your contribution.
I am interested in MPCC and want to run on C++ execution on the Ubuntu 18.04.  According to your README, I tried to make the CMakeLists but failed like following:

![image](https://user-images.githubusercontent.com/12562147/156922979-8d06d420-753b-41d9-8c3f-f0e7bc9e6ac5.png)

After failed to make, I changed the CMakeLists and finally succeeded to build. But, I encountered the problem when I launched with './MPCC'. I found that problem is associated with [matplotlib-cpp](https://github.com/lava/matplotlib-cpp). However, I couldn't find the solution although strive to solve this problem with some modification and trials.
![image](https://user-images.githubusercontent.com/12562147/156923072-e9986bd3-9942-4224-9232-28a27b98ffe1.png)

Let me know what is the problem if possible.

**Comment by alexliniger** [comment]
the two branches use different approaches for matplotlib-cpp in the CMake file, can you try out the other one as well. I will have a look as soon as possible. But over the years I had also several times issues with matplotlib-cpp.
Best,
Alex

**Comment by Geonhee-LEE** [comment]
Thanks for your reply.
I tried to change from `master` branch to `/wip/install-target` branch. It also happened a same problem. 
![image](https://user-images.githubusercontent.com/12562147/156947399-56e3e218-f4f6-413e-86c0-5e0ca9c61b9d.png)

**Comment by Geonhee-LEE** [comment]
- The python configurations:
  ![image](https://user-images.githubusercontent.com/12562147/156947753-750a233a-0f74-4225-9cca-60a6b8f35066.png)
  
  ![image](https://user-images.githubusercontent.com/12562147/156947780-914fe0f7-96b4-4bcb-b717-1d841594ef08.png)

- Modified CMakeLists:
  ```cmake
  cmake_minimum_required(VERSION 3.7)
  project(MPCC)
  
  set(CMAKE_CXX_STANDARD 14)
  set(CMAKE_CXX_FLAGS "-O2")
  
  find_package(PythonLibs REQUIRED)
  include_directories(${PYTHON_INCLUDE_DIRS})
  
  include_directories(.)
  include_directories(External/blasfeo/lib/include)
  include_directories(External/hpipm/lib/include)
  include_directories(External/matplotlib)
  include_directories(External/Eigen)
  include_directories(External/Json/include)
  
  add_executable(MPCC
          main.cpp
          types.cpp
          types.h
          config.h
          Params/params.cpp
          Spline/cubic_spline.cpp
          Spline/arc_length_spline.cpp
          Interfaces/hpipm_interface.cpp
          Interfaces/solver_interface.cpp
          Constraints/constraints.cpp
          Constraints/bounds.cpp
          Cost/cost.cpp
          Model/model.cpp
          Model/integrator.cpp
          Tests/spline_test.cpp
          Tests/cost_test.cpp
          Tests/model_integrator_test.cpp
          Tests/constratins_test.cpp
          MPC/mpc.cpp
          Params/track.cpp
          Params/track.h
          Plotting/plotting.cpp
          Plotting/plotting.h)
  
  
  #find_package(Python COMPONENTS Development)
  #target_include_directories(MPCC PRIVATE ${Python_INCLUDE_DIRS} ${Python_INCLUDE_DIRS})
  #target_link_libraries(MPCC ${Python_LIBRARIES} )
  
  target_link_libraries(MPCC ${CMAKE_SOURCE_DIR}/External/hpipm/lib/lib/libhpipm.a ${CMAKE_SOURCE_DIR}/External/blasfeo/lib/lib/libblasfeo.a ${PYTHON_LIBRARIES} )
  ```

**Comment by Geonhee-LEE** [comment]
Hi, @alexliniger 
I finally correct the problem for matplotlib.
But, I want to launch the MPCC path tracking online like README :

https://github.com/alexliniger/MPCC/blob/master/Images/MPC_sim.gif
