### ISSUE TITLE
cost function

### ISSUE THREAD

**Issue by wulemao** [alexliniger/MPCC#74]
Hello! In matlab code,the objective function form is 
<img width="412" alt="image" src="https://user-images.githubusercontent.com/36061456/161540738-73cea305-59bb-4797-9e09-ae33f1fc89e8.png">
However, in the paper the objective function form is 
<img width="622" alt="image" src="https://user-images.githubusercontent.com/36061456/161540972-10417793-bffe-477b-9518-f14132fcec58.png">
It seems that there are some differences between the two in the state variables and the  objective function members, which confuses me a lot.Could you explain it to me how to derive the objective function in the MATLAB code from the objective function in the paper, thank you very much.

**Comment by alexliniger** [comment]
Q_k contains basically the contouring error + lag error term (plus some regularization cost on u_k the actual inputs, and the yaw rate and the slip angle (see the AMZ paper)) 

f_k contains c_k and γ (the γ v_k T_s term)

R_k is R -> U in the code is the derivative of u and not the difference as in the paper

Q_N+1 and f_N+1 are the terminal cost terms, which use higher values for the contouring cost

Generally, the Matlab code and especially the C++ code are improved versions of the code from the paper.
