### ISSUE TITLE
Using Hpipm in Matlab

### ISSUE THREAD

**Issue by dreamonJure** [alexliniger/MPCC#76]
Hello, @alexliniger 
Appreciate your contribution for the excellent work.

When trying to use Hpipm interface in Matlab, something went wrong. The error information is "ocp_qp_dim_create cannot be found". I have put the downloaded package '[hpipm](https://github.com/giaf/hpipm)' in the folder defined in env.sh and run 'source env.sh' before starting Matlab in terminal. Could you please give me some help.?

**Comment by alexliniger** [comment]
Sorry I have no longer access to Matlab
