### ISSUE TITLE
Build instructions for new CppAD-codegen

### ISSUE THREAD

**Issue by ckurtz22** [alexliniger/MPCC#82]
There is a lack of build instructions or process for the new CppAD-codegen branch (or docs in general for that matter :P ). 
I've managed to fumble most of the way so far on my own to get a "successful" build but now getting runtime errors when I run the main executable MPCC. Also, not sure if I need to build the contents of the ADCodeGen folder or not, but cannot seem to get this folder to build.

**Comment by alexliniger** [comment]
Sorry I know, I will add instructions and plan to add a docker container:

**These instructions are not tested, but is what I remember plus some old personal documentation**

### Installation:
Compared to the instructions for the other branches:
build blasfeo and hpipm into root with cmake following their changed instructions

CppAD:
```
Download CppAD
cd in folder
mkdir build
cd build
cmake ..
sudo make install
```
I think you can also use `sudo apt install cppad`

CppAD CodeGen
```
git clone https://github.com/joaoleal/CppADCodeGen.git CppADCodeGen
cd in folder
mkdir build
cd build
cmake ..
sudo make install
```

### Build:

Build CppAD Libs:
```
cd ADCodeGen
mkdir build
cd build
cmake ..
make
./ADCodeGen
```

Build MPCC:
```
mkdir build
cd build
cmake ..
make
./MPCC
```

**Comment by ckurtz22** [comment]
Great, thank you!

**Comment by ckurtz22** [comment]
Well my issue turned out to be silly anyways, I was building from the C++ dir like the other branches instead of C++/build :)

**Comment by ckurtz22** [comment]
#84 kinda fixes this as it adds the steps needed to the install script

**Comment by alexliniger** [comment]
Thanks for updating the install instructions. I will test everything as soon as I have time and approve the merge requests.
