### ISSUE TITLE
What is ZHO?

### ISSUE THREAD

**Issue by ziyi-joe** [alexliniger/MPCC#88]
Hi!  Thank u so much for the perfect work!
I have a question about the ZHO you mention in the model.cc
https://github.com/alexliniger/MPCC/blob/bd331621ba47ae3326711922a863bdb1cdf2d2ea/C%2B%2B/Model/model.cpp#L282
Do you mean ZOH(Zero-Order Hold)?
BTW, I have never seen the integrator in the discretizeModel. It i concise and precise. Could you give some reference? I'd like to learn about it, but I didn't find it on Google.

**Comment by alexliniger** [comment]
Yes it is zero order hold, and what I use is the matrix exponential.
The matrix exponential is the exact discretization of the linear system, for nonlinear system it is not exact. However, it is definitly more accurate than euler forward.
In the new automatic diff branch I am using RK4 for all discretizations.
